apiVersion: v1
kind: Pod
metadata:
  name: stress-ng-pod
spec:
  containers:
  - name: stress-ng
    image: ghcr.io/colinianking/stress-ng 
    command: ["stress-ng"]
    args: ["--vm", "1", "--vm-bytes", "1G", "--vm-keep"]
  restartPolicy: Never